### ISSUE TITLE
watch and bind

### ISSUE THREAD

**Issue by mikkoh** [robin-allen/frp.js#1]
I think this module is fantastic.

I'm wondering why map the same function to both `watch` and `bind`.

Personally I'm in favour of just using `watch` since `Function.bind` already exists and it may cause issues in the future while working on a project.

"Is developer X binding a `Function` or an `frp.event`?"

**Comment by rogual** [comment]
Hey, good question! `watch` and `bind` do different things on `signal` but the same thing on `event`. `watch` means “tell me when this thing changes” and `bind` means “tell me this thing's current value, then also tell me when it changes”.

Since `event` has no concept of a “current value” (that's really the only difference between it and `signal`) I decided to implement `event.bind` as just an alias for `event.watch`. That way you can say `x.watch` or `x.bind` without knowing what `x` is, and you'll get a set of semantics that (to me at least) make some sort of sense.

I'm not totally satisfied that this is the best thing to do — maybe `event` should only have `watch` and `signal` should only have `bind`. Still thinking about it; would welcome suggestions.

**Comment by mikkoh** [comment]
Ok cool. Thanks for the reply. That makes a lot of sense. No I think it's good to have the API be as similar as possible for `event` and `signal`.

Sorry for the late reply. I've been in Christmas mode.

**Comment by rogual** [comment]
No worries; thanks for your interest.
